### ISSUE TITLE
SASS - Beautyfiy not working

### ISSUE THREAD

**Issue by insab** [n33/skel#153]
windows 10

downloaded from here -http://www.sublimetext.com/2
Windows 64 bit .

Traceback (most recent call last):
  File ".\SassBeautify.py", line 198, in <lambda>
  File ".\SassBeautify.py", line 201, in check_thread
  File ".\SassBeautify.py", line 221, in handle_process
AttributeError: 'NoneType' object has no attribute 'splitlines'

**Comment by n33** [comment]
Probably not a Skel issue. Might want to check out the Sublime Text 3 beta.
